site_name: Documentación web general   #name of proyect JOHN
nav:
    - Inicio: index.md
    - MarkDown:
        - Markdown sintaxis: MarkDown/guiaBasicaMarkDown.md
        - Markdown 'Mkdocs': MarkDown/manualMkdocs.md
    - Nevegadores y sitios web:
        - Conceptos básicos: NavegadoresYSitiosWeb/00_Conceptos.md
        - Conceptos HTML: NavegadoresYSitiosWeb/01_Conceptos_Html.md
    - Tecnologias de desarrollo web:
        - JSON web token: TecnologiasDeDesarrollo/01_JWT.md
    # - Resumen de opciones: opc/opciones.md
theme: readthedocs
site_dir: Markdown