site_name: firstProyect   #name of proyect JOHN
nav:
    - Inicio: index.md
    - MarkDown:
        - markdown comandos: MarkDown/guiaBasicaMarkDown.md
        - markdown Mkdocs: MarkDown/manualMkdocs.md
    - Nevegadores y sitios web:
        - Conceptos básicos: Navegadores y sitios web/00_Conceptos.md
        - Conceptos HTML: Navegadores y sitios web/01_Conceptos_Html.md
    # - Resumen de opciones: opc/opciones.md
theme: readthedocs
site_dir: Markdown